### ISSUE TITLE
[Fix] 프론트팀 내부 코드리뷰 피드백 후 리팩토링

### ISSUE THREAD

**Issue by osohyun0224** [ReHab-Web/ReHab-FrontEnd#18]
### Description
> pull request를 보며 팀 내부 코드리뷰 후 수정사항에 관한 피드백을 통해 리팩토링을 진행한다.

### In Progress
> 작업사항들을 작성해주세요.
- [x] 백엔드 api 명세 확인 후 더미데이터 수정
- [ ] css 컴포넌트 간 위치 설정으로 코드 변경
- [ ] 강의 별 시간을 dayjs로 구현

**Comment by PortalCube** [comment]
#40 으로 병합합니다.
