### ISSUE TITLE
[Doc/FE/AI] 사용자 웹캠을 녹화하는 MediaRecorder 특성에 관해

### ISSUE THREAD

**Issue by PortalCube** [ReHab-Web/ReHab-FrontEnd#27]
# Description
@insung3511 AI에서 수신 받는 영상이 어떠한 영상인지에 대한 상세한 정보를 공유할 필요가 있을 것 같아, 프론트에서 MediaRecorder로 녹화한 영상의 데이터에 대해서 정리해서 적었습니다.

# Document

### MediaRecorder가 녹화하는 파일 형식에 대해

찾아본 결과, 크롬, 파이어폭스, 엣지와 같은 대중적인 브라우저들에서 MediaRecorder는 아래의 형식만을 지원합니다.

```
video/webm;codecs=vp8
video/webm;codecs=vp9
video/webm;codecs=h264
video/webm;codecs=av1
video/x-matroska;codecs=vp8
video/x-matroska;codecs=vp9
video/x-matroska;codecs=h264
video/x-matroska;codecs=av1
```
(Source: https://stackoverflow.com/questions/41739837/all-mime-types-supported-by-mediarecorder-in-firefox-and-chrome)

mp4, avi 같은 컨테이너는 지원하지 않으며, 컨테이너는 webm와 mkv를 지원합니다. 코덱 역시도 vp9, av1 과 같은 최신 코덱 위주로 지원합니다.

각 코덱에 대해서 MediaRecorder가 녹화한 파일을 여기에 올려드립니다. 

[av1.webm](https://github.com/ReHab-Web/ReHab-FrontEnd/assets/35104213/085271a3-dab3-428b-a289-bc0dd56b9fe1)
[h264.webm](https://github.com/ReHab-Web/ReHab-FrontEnd/assets/35104213/3e52faaf-b665-4eda-b37c-d9bff5deaef5)
[vp8.webm](https://github.com/ReHab-Web/ReHab-FrontEnd/assets/35104213/b99f00fe-4ed0-4213-b441-760127d38027)
[vp9.webm](https://github.com/ReHab-Web/ReHab-FrontEnd/assets/35104213/c2c4c423-824b-4140-9361-bd4129225832)

아마 최종본에서는 **H264 코덱**을 사용할 것 같습니다.

### MediaRecorder가 녹화한 파일은 영상 길이에 대한 메타데이터가 누락됨

MediaRecorder로 녹화를 하다보니 알게된 사실인데, MediaRecorder로 녹화한 파일에는 영상 길이에 대한 메타데이터가 존재하지 않습니다. 이 때문에 일반적인 동영상 플레이어로 재생하면 재생 시간이 정상적으로 표시되지 못합니다.

찾아보니, 이것도 MediaRecorder가 WebM의 live 포맷으로 영상을 녹화하기 때문이라고 합니다. [WebM의 live 포맷은 의도적으로 영상의 총 길이를 명시하지 않는다고 하네요.](https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/modules/mediarecorder/README.md?autodive=0%2F%2F%2F%2F#the-produced-recording-doesn_t-have-duration-or-is-not-seekable)

단순히 길이에 대한 정보를 별도로 표기하지 않았을 뿐, 동영상에서 이미지를 뽑는데에는 아마 문제가 없을 것 같습니다.

### MediaRecorder로 정확히 n초를 녹화하는게 가능한가?

결론부터 말씀드리자면, 힘들 것 같습니다. MediaRecorder로 녹화한 4개의 영상의 시간을 확인해본 결과, 모두 15초보다 약간 짧았습니다. (14.8초, 14.9초 정도)

프론트에서는 MediaRecorder의 timeslice를 15000ms로 세팅하여 15초로 자르도록 코드를 설정해둔 상태지만, 아마 Javascript의 성능 한계상 MediaRecorder의 내부 로직이 시간 정확도를 살짝 포기하는 것 같습니다.

고작 0.1초 ~ 0.3초 정도의 오차지만, AI에서 어떻게 처리하는지에 따라 큰 문제가 될 수도 있어서 미리 말씀드립니다.

### 프론트에서 자체적으로 MediaRecorder로 녹화한 영상의 길이를 자르거나 코덱을 바꿀 수 없는가??

프론트에서 녹화한 데이터는 일반적인 Javascript로는 바이너리 데이터에 대한 조작밖에 할 수가 없습니다. 길이를 조작하거나 코덱을 바꿀려면 영상의 프레임 데이터에 접근이 가능해야하는데, 이는 영상의 디코딩 과정을 요구합니다.

영상을 디코딩하고 인코딩하는데 대표적인 라이브러리인 ffmpeg를 Javascript와 WebAssembly를 이용하여 구동할 수 있는 [ffmpeg.wasm](https://github.com/ffmpegwasm/ffmpeg.wasm)을 사용하면 프론트에서도 영상을 디코딩하여 길이를 조작하거나 코덱을 바꿀 수 있지만, 네이티브에 비해서는 성능이 매우 딸립니다. MediaRecorder로 녹화한 H264 코덱의 15초 영상을 네이티브 ffmpeg로는 2초만에 인코딩을 완료했으나, ffmpeg.wasm으로 mp4로 인코딩한 결과 91초가 걸렸습니다.

**Comment by insung3511** [comment]
우선 이렇게 깔끔히 정리해주셔서 진심으로 감사합니다... 진짜 감사합니다...
우선 파일은 `video/webm;codecs=h264` 이나 `video/webm;codecs=av1` 로 주시면 될거 같습니다. 둘 다 동일한 방식으로 진행되는 것으로 알고 있어서 한번 확인해보고 코멘트 드리겠습니다.

영상 길이는 원래 메타데이터가 아닌 bytes로 갖고와서 다 끝날때까지 다 갖고오는 편이라 문제가 될거 같진 않습니다. 영상길이는 0.1초 차이는 직접 시연하고 실험 과정에서 수정되어야할거 같네요.

별계로 궁금한 점이 있습니다. ffmpeg를 저도 사용하여 디코딩을 하고 있는데 혹시 쓰고 계신 방법이 ffmpeg 인가요? 만일 그렇다면 H264 코텍은 mp4로 인코딩 된 것을 말씀하신걸까요?

**Comment by PortalCube** [comment]
@insung3511 맞습니다! 제 개인 노트북에서 ffmpeg로 h264.webm을 단순히 output.mp4로 인코딩시켰을때, 2초가 걸렸습니다.

조금 더 상세히 설명을 드리자면, video/webm;codecs=h264 형식 (webm 컨테이너, h264 코덱) 으로 MediaRecorder로 웹캠을 녹화한뒤, 녹화된 결과물인 h264.webm을 output.mp4로 인코딩했습니다!

**Comment by insung3511** [comment]
좋습니다. 우선 알아두시면 좋을거 같아 말씀드리면... AI Server 단에서는 아래와 같이 요청 영상을 처리합니다.

1. Client layer에서 request 영상을 보내줌
2. FastAPI에서는 업로드된 파일은 `tempfile.SpooledTemporaryFile`로 처리됨. Bytes로 변환 후 local 내에 임시 생성.
3. OpenCV cv2.VideoCapture() 를 이용하여 Stream 객체 생성
4. 임시 생성한 영상 파일 제거

위와 같이 작동됨으로 mp4나 webm 둘 중 하나로 보내주시는걸로 알겠습니다. 확장자는 상관 없고 코덱은 무난히 h264가 가장 좋을거 같습니다. 확인 시, 이모지나 comment 부탁드립니다.

**Comment by insung3511** [comment]
우선 Database에 영상 길이를 저장하고 제가 직접 자르는 것으로 결정 났습니다. 영상 길이는 Frame 단위로 이해하시면 될거 같습니다. 간단히 설명만 추가하고 Close하겠습니다.

## Why video length have to be frame?

![image](https://github.com/ReHab-Web/ReHab-FrontEnd/assets/17959335/c8961c3c-5535-4995-94f6-4da10fc22df5)

가장 큰 이유는 인공지능에서는 영상이든 뭐든 다 숫자로 해석하기 때문입니다. 영상은 이미지가 합쳐진 형태, 이미지는 (보통) 3개의 채널로 합쳐진 형태, 각 채널은 색상 정보를 나타내고 있는 행렬입니다. 그러므로 여러 이미지 (행렬)이 합쳐지면 영상 (텐서)로 변하기 때문에 인공지능에서는 이를 숫자의 조합으로 해석합니다. 프레임 개수는 행렬의 높이 혹은 길이로 해석하시면 됩니다.

여러 이미지가 합쳐져 있다면 당연하게도 영상이 될터이니 여러 행렬이 합쳐지면 텐서가 되기 때문에 텐서의 길이를 알아야 합니다. 그래서 Frame 단위로 넣은 것이니 알아두시면 좋을 것 같습니다.

## What happend while AI get vidoes?

![image](https://github.com/ReHab-Web/ReHab-FrontEnd/assets/17959335/186c8e67-ab9b-4ad6-8ed9-286f3ed7f448)

영상을 입력 받은 후에는 사실 텐서를 모두 인공지능에게 넣어줘도 됩니다. 현재 기능상의 이유로 각 프레임 별로 넣어주고 있습니다. 그러니 실질적으로는 위 이미지와 같이 작동되어 Skeleton을 추출하게 된다라고 이해하시면 편하실거 같습니다.
