### ISSUE TITLE
[FE/BE/AI] 최종 기능 명세서를 확정한다.

### ISSUE THREAD

**Issue by osohyun0224** [ReHab-Web/ReHab-FrontEnd#7]
### Description
> 기존 기능 명세서에서 0824 기능 회의로 재정의된 기능들을 명확히하여 최종 기능 명세서를 확정한다.

### In Progress
> 작업사항들을 작성해주세요.
- [x] 기능 명확히 분류
- [x] 최종 명세서 작성
- [x] 모든 개발자 필수 전체 확인

### ETC
> 기타사항

**Comment by osohyun0224** [comment]
[Re:Hab 최종 기능 명세서](https://www.notion.so/osohyun/Re-Hab-b704572b2dce422ba572fca8a824fac4)

**Comment by osohyun0224** [comment]
> [Re:Hab 최종 기능 명세서](https://www.notion.so/osohyun/Re-Hab-b704572b2dce422ba572fca8a824fac4)
@jyp-on 
@PortalCube 
@Sirius506775 
@insung3511

**Comment by insung3511** [comment]
@osohyun0224 AI는 크게 확인할 내용이 없어 보입니다. 혹시 제가 놓친 부분이 따로 있을까요?

**Comment by osohyun0224** [comment]
@insung3511 아하.. 제가 AI쪽 기능을 놓친 것 같네요.. 혹시 인성님 ai 쪽 기능 명세 부탁드려도 될까요..? 🥹

**Comment by insung3511** [comment]
물론 입니다. 작성 후에 다시 한번 카카오톡이나 Comment로 말씀드리겠습니다. 감사합니다.
